# Generated by Django 4.0 on 2021-12-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_place_delete_bolvanka'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='enemy',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
