# Generated by Django 4.0 on 2021-12-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='damage',
            field=models.IntegerField(default=0),
        ),
    ]
