# Generated by Django 4.0 on 2021-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_alter_enemy_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('damage', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('classification', models.CharField(max_length=21)),
                ('block_chance', models.FloatField(default=0)),
                ('dodge_chance', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(max_length=21),
        ),
    ]
