# Generated by Django 4.0 on 2021-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_weapon_alter_enemy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ad_damagee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='ad_dod_chancee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='first_hite',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='near_fight_dmge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='second_chancee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='block_chance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dodge_chance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
