# Generated by Django 4.0 on 2021-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_weapon_ad_damagee_weapon_ad_dod_chancee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='near_fight_dmge',
            field=models.FloatField(default=0, null=True),
        ),
    ]
