# Generated by Django 4.0 on 2021-12-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_alter_weapon_near_fight_dmge'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='crit_chance',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
