# Generated by Django 4.0 on 2021-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_weapon_crit_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=21)),
                ('damage', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0, null=True)),
                ('drop', models.CharField(max_length=21)),
            ],
        ),
    ]
